service: nombre-del-proyecto

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1  # Cambia esto a la región más cercana a Lima, Perú
  stage: dev  

functions:
  listarMensajesActivos:
    handler: src/handlers/listarMensajesActivos.listarMensajesActivos
    events:
      - http:
          path: /mensajes-activos
          method: get
          cors: true

  programarCampania:
    handler: src/handlers/programarCampania.programarCampania
    events:
      - http:
          path: /programar-campania
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000  # Puerto en el que se ejecutará localmente
